### ISSUE TITLE
Not working with css as an entry point & webpack 4

### ISSUE THREAD

**Issue by sapkra** [shepherdwind/css-hot-loader#50]
The page fully reloads when I'm changing the scss file and I get the following warning.

```console
[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because ./sass/style.scss is not accepted
Update propagation: ./sass/style.scss -> 5
    at hotApply (http://localhost:5000/webpack/css/style.js:526:30)
    at http://localhost:5000/webpack/css/style.js:364:22
```

Here the relevant parts from my webpack config:
```javascript
entry: {
        'css/style': './sass/style.scss',
},
plugins: [
        new MiniCssExtractPlugin({
            filename: '[name].css',
            allChunks: true,
        }),
],
module: {
        rules: [
            {
                test: /\.scss$/,
                include: [
                    path.resolve(paths.sources.sass),
                ],
                use: [
                    'css-hot-loader',
                    MiniCssExtractPlugin.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            url: false,
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'sass-loader',
                        options: { sourceMap: true }
                    },
                ]
            },
        ]
}
```

**Comment by shepherdwind** [comment]
There are some in this repo https://github.com/shepherdwind/css-hot-loader/tree/master/examples . Can you provide me a tiny example code ? So I can reproduce your problem , the config you provide is just not easy for me to find out solution.

**Comment by sapkra** [comment]
https://github.com/sapkra/css-hot-loader-test

Just enable "Preserve log" in your browser console and change the color of the headline in the `style.scss`

**Comment by shepherdwind** [comment]
Try latest version 1.4.2 .  This problem fixed.

**Comment by sapkra** [comment]
It's working now. Thanks a lot for your quick support.
